config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'

  resources :articles do
    resources :cards, only: [:new, :create]
  end
  resources :boards do
    resources :comments, only: [:new, :create]
  end
  resources :cards

  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_one_attached :eyecatch
    
    validates :title, presence: true
    validates :content, presence: true
    
    has_many :cards, dependent: :destroy
    has_many :comments, dependent: :destroy
    belongs_to :model
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :article
    validates :content, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
    validates :content, presence: true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :articles, dependent: :destroy
  has_one :profile, dependent: :destroy

  def has_written?(article)
    articles.exists?(id: article.id)
  end

  def display_name
    profile&.nickname || self.email.split('@').first
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end

  def prepare_profile
    profile || build_profile
  end

  
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :model
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show]
    before_action :authenticate_model!, only: [:new, :create, :edit, :update, :destroy]

    def index
        @articles = Article.all.order("id DESC")
        
    end

    def show
        @cards = @article.cards
    end

    def new
        @article = current_model.articles.build

    end

    def create
        @article = current_model.articles.build(article_params)
        if @article.save
          redirect_to article_path(@article), notice: 'Save complete'
        else
          flash.now[:error] = 'save error'
          render :new
        end
    end

    def edit
        @article = current_model.articles.find(params[:id])
    end

    def update
        @article = current_model.articles.find(params[:id])
        if @article.update(article_params)
        redirect_to article_path(@article), notice: 'update successful!!'
        else
            flash.now[:error] = 'update failed'
            render :edit
        end
    end

    def destroy
        article = current_model.articles.find(params[:id])
        article.destroy!
        redirect_to root_path, notice: 'delete successful!!'
    end


    private
    def article_params
        params.require(:article).permit(:title, :content, :eyecatch)
    end

    def set_article
        @article = Article.find(params[:id])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    def show
        @article = Article.find(params[:id])
        @comments = @article.comments
    end
    
    def new
    end

    private
    def board_params
        params.require(:board).permit(:title, :content, :eyecatch)
    end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

    def new
        article = Article.find(params[:article_id])
        @card = article.cards.build
    end

    def create
        article = Article.find(params[:article_id])
        @card = article.cards.build(card_params)
        if @card.save
          redirect_to article_path(article), notice: 'Add card'
        else
          flash.now[:error] = 'Could not update'
          render :new
        end
      end
    private
    def card_params
        params.require(:card).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        board = Article.find(params[:board_id])
      @comment = board.comments.build
    end
    def create
        board = Article.find(params[:board_id])
        @comment = board.comments.build(comment_params)
        if @comment.save
          redirect_to board_path(board), notice: 'Add Cmments'
        else
          flash.now[:error] = 'Could not update'
          render :new
        end
      end
      private
      def comment_params
        params.require(:comment).permit(:content)
      end
      end

app/controllers/concerns/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show]
    before_action :authenticate_model!, only: [:new, :create, :edit, :update, :destroy]

    def index
        @articles = Article.all
    end

    def show
    end

    def new
        @article = current_model.articles.build
    end

    def create
        @article = current_model.articles.build(article_params)
        if @article.save
          redirect_to article_path(@article), notice: 'Save complete'
        else
          flash.now[:error] = 'save error'
          render :new
        end
    end

    def edit
        @article = current_model.articles.find(params[:id])
    end

    def update
        @article = current_model.articles.find(params[:id])
        if @article.update(article_params)
        redirect_to article_path(@article), notice: 'update successful!!'
        else
            flash.now[:error] = 'update failed'
            render :edit
        end
    end

    def destroy
        article = current_model.articles.find(params[:id])
        article.destroy!
        redirect_to root_path, notice: 'delete successful!!'
    end


    private
    def article_params
        params.require(:article).permit(:title, :content, :eyecatch)
    end

    def set_article
        @article = Article.find(params[:id])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_model!
  
    def show
      @profile = current_model.profile
    end
  
    def edit
        @profile = current_model.build_profile
    end

    def update
        @profile = current_model.build_profile
        if @profile.save
          redirect_to profile_path, notice: 'profile update'
        else
          flash.now[:error] = 'update error'
          render :edit
        end
      end
  
      private
      def profile_params
          params.require(:profile).permit(
            :nickname,
            :introduction,
            :avatar
          )
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.haml
= link_to article_path(article)  do
  .card
    .card_content
      .card_title
        %p Brackets
    .card_content
      .card_text
        = article.title
        .card_detail
          = image_tag 'Oval1.png'

app/views/articles/_form.html.haml
.container
  %ul
    - article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: article, url: articles_path, method: 'post', local: true) do |f|
    %div
      = f.label :eyecatch, 'eyecatch'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/articles/edit.html.haml
.container
  %ul
    - @article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @article, url: article_path(@article), method: 'put', local: true) do |f|
    %div
      = f.label :eyecatch, 'eyecatch'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/articles/index.html.haml
.container
  %h2 All Boards
  - @articles.each do |article|
    = render 'article', article: article
  
.container           
  = link_to new_article_path do
    .card
      .card_content
        .card_create
          %h1 +Add new borad
  %div
          

app/views/articles/new.html.haml
.container
  %ul
    - @article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @article, url: articles_path, method: 'post', local: true) do |f|
    %div
      = f.label :eyecatch, 'eyecatch'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/articles/show.html.haml
.container
  %h2 Brackets
= link_to board_path(@article)  do
  .article
    - if @article.eyecatch.attached?
      .card_image
        = image_tag @article.eyecatch
    %h1.article_title= @article.title
    - if model_signed_in? && current_model.has_written?(@article)
      .article_detail_actions
        .dropdown
          = image_tag 'Combined Shape.svg', class: 'dropbtn'
          .dropdown-content.mini
            = link_to 'Edit', edit_article_path(@article)
            = link_to 'Delete', article_path(@article), data: { method: 'delete', confirm: 'Delete OK？' }
    .article_content
      = @article.content
    .article_detail
      = image_tag 'Oval1.png'
      %div

.article
  %h2 card list
  - @cards.each do |card|
    .article_card_title
      %p= card.title
    %ul
      .article_card_content
        %li= card.content

.container           
  = link_to new_article_card_path(@article) do
    .card
      .card_content
        .card_create
          %h1 +Add new card

app/views/boards/show.html.haml
.container
  %h2 Card
  .article_detail_actions
    -# .dropdown
    -#   = image_tag 'Combined Shape.svg', class: 'dropbtn'
    -#   .dropdown-content.mini
    -#     = link_to 'Edit', edit_article_path(@article)
    -#     = link_to 'Delete', article_path(@article), data: { method: 'delete', confirm: 'Delete OK？' }
  - if @article.eyecatch.attached?
    .article_image
      .article_photo
        = image_tag @article.eyecatch
.article
  %h1.article_title= @article.title
  .article_content
    = @article.content
  
    

.article
  .article_list
    %h2 List of comments
    - @comments.each do |comment|
      %ul
        .article_comment
          %li= comment.content

.container           
  = link_to new_board_comment_path(@article) do
    .card
      .card_content
        .card_create
          %h1 +Add new comment

app/views/cards/new.html.haml
.container
  %ul
    - @card.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @card, url: article_cards_path(@card.article), local: true) do |f|
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'New Card'
    %div
      = f.text_area :content
    = f.submit 'submit', class: 'text'

app/views/comments/new.html.haml
.container
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @comment, url: board_comments_path(@comment.article), local: true) do |f|
    %div
      = f.label :content, 'New Comment'
    %div
      = f.text_area :content
    = f.submit 'submit', class: 'text'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width,initial-scale=1.0", :name => "viewport"}/

  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          = link_to :back do
            = image_tag 'back.svg', class: 'header_back'
        %p.header_pageTitle
          = link_to 'Boards', root_path
      - if model_signed_in?
        .dropdown
          = image_tag 'Oval1.png', class: 'header_avatar dropbtn'
          .dropdown-content
            
            = link_to 'log out', destroy_model_session_path, data: { method: 'delete' }
      - else
        = link_to 'login', new_model_session_path, class: 'header_loginBtn'
    %p.notice= notice
    %p.alert= alert
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/profiles/edit.html.haml
.contaner
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div
      = f.label :avatar, 'avatar'
    %div
      = f.file_field :avatar
    
    %div
      = f.label :nickname, 'nickname'
    %div
      = f.text_field :nickname, class: 'text'
    %div
      = f.label :introduction, '自己紹介'
    %div
      = f.text_area :introduction

    = f.submit '保存', class: 'btn-primary'

app/views/profiles/show.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_image
      = image_tag 'Oval.png'
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          = current_model.display_name
        .profilePage_user_actionButton
          = link_to 'Edit', edit_profile_path
      .profilePage_user_introduction
        =current_model.profile&.introduction

  - current_model.articles.each do |article|
    = render 'article', article: article
    
        